CREATE TABLE MUSIQUE (
  IdM INT NOT NULL AUTO_INCREMENT,
  Titre VARCHAR(255) NOT NULL,
  Artiste VARCHAR(255) NOT NULL,
  Genre VARCHAR(255) NOT NULL,
  AnneeSortie YEAR NOT NULL,
  Langue VARCHAR(255) NOT NULL,
  PRIMARY KEY (IdM)
);
